version: '3'
services:
  labor-exchange.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - ${APP_PORT}:8000
    env_file:
    - ./.env
  labor-exchange.postgres:
    image: postgres:latest
    hostname: labor-exchange.postgres
    container_name: labor-exchange.postgres
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
    - ./.env
volumes:
  pgdata:
